---
##########################
## Hadolint config file ##
##########################
ignored:
  # Last USER should not be root
  - DL3002
  # Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
  - DL3008
  # - DL3002
  # Delete the apt lists (/var/lib/apt/lists) after installing something
  - DL3009
  # Multiple consecutive `RUN` instructions. Consider consolidation.
  - DL3059
